# -----------------------------------------------------------------------
# @Data Engineer: Leonardo Galler - leolacerdagaller@live.com
# @Client: Gerda Berentaite
# @note: Create a Spark Cluster on docker
# @info: This YML file is based on the following YMLs
#   - https://raw.githubusercontent.com/cluster-apps-on-docker/spark-standalone-cluster-on-docker/master/docker-compose.yml
#   - https://raw.githubusercontent.com/bitnami/bitnami-docker-spark/master/docker-compose.yml
#-----------------------------------------------------------------------
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
services:
  jupyterlab:
    image: jupyter/pyspark-notebook
    container_name: jupyterlab
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - /opt/workspace:/opt/workspace
      - /home/leogaller/Documentos/freela/upwork/gerda-ecommerce-pyspark:/home/jovyan/work
  spark-master:
    image: docker.io/bitnami/spark:3.2.1
    container_name: spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - 8081:8080
      - 7077:7077
    volumes:
      - /opt/workspace:/opt/workspace
  spark-worker-1:
    image: docker.io/bitnami/spark:3.2.1
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - 8082:8081
    volumes:
      - /opt/workspace:/opt/workspace
  spark-worker-2:
    image: docker.io/bitnami/spark:3.2.1
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - 8083:8081
    volumes:
      - /opt/workspace:/opt/workspace
  spark-worker-3:
    image: docker.io/bitnami/spark:3.2.1
    container_name: spark-worker-3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - 8084:8081
    volumes:
      - /opt/workspace:/opt/workspace
  spark-worker-4:
    image: docker.io/bitnami/spark:3.2.1
    container_name: spark-worker-4
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - 8085:8081
    volumes:
      - /opt/workspace:/opt/workspace
...